In [32]:
import pandas as pd
train=pd.read_csv("train.csv")
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [34]:
Q1= train["Age"].quantile(0.25)
Q3= train["Age"].quantile(0.75)
IQR= Q3-Q1
lower_bound= Q1-1.5*IQR
upper_bound= Q3+1.5*IQR
outlier=train[((train["Age"] < lower_bound) | (train["Age"] > upper_bound))]




# train.info()

In [35]:
len1=len(train["Age"])

In [37]:
print(f"le nombre d'oulier est : {outlier.shape[0]}")

le nombre d'oulier est : 11

In [ ]:
train=train[((train["Age"] >= lower_bound) & (train["Age"] <= upper_bound))]
len2=len(train["Age"])
nb_outliers=len1-len2
print("Nombre d'outliers: ",nb_outliers)

In [57]:
weather = pd.read_csv("weatherHistory.csv")
weather.info()
weather.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object
dtypes: float64(8), object(4)
memory usage: 8.8+ MB

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [42]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\blond\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.3)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp313-cp313-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ------- -------------------------------- 2.1/11.1 MB 11.1 MB/s eta 0:00:01
   ------------- -------------------------- 3.7/11.1 MB 9.3 MB/s eta 0:00:01
   ------------------ --------------------- 5.2/11.1 MB 8.5 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.1 MB 8.1 MB/s eta 0:00:01
   ------------------------------ --------- 8.4/11.1 MB 8.1 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.1 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 7.7 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl (41.0 MB)
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   - -------------------------------------- 1.8/41.0 MB 8.8 MB/s eta 0:00:05
   --- ------------------------------------ 3.9/41.0 MB 9.6 MB/s eta 0:00:04
   ----- ---------------------------------- 6.0/41.0 MB 9.8 MB/s eta 0:00:04
   -------- ------------------------------- 8.4/41.0 MB 10.0 MB/s eta 0:00:04
   ---------- ----------------------------- 10.7/41.0 MB 10.2 MB/s eta 0:00:03
   ------------ --------------------------- 13.1/41.0 MB 10.4 MB/s eta 0:00:03
   --------------- ------------------------ 15.5/41.0 MB 10.6 MB/s eta 0:00:03
   ----------------- ---------------------- 18.1/41.0 MB 10.8 MB/s eta 0:00:03
   ------------------- -------------------- 20.2/41.0 MB 10.7 MB/s eta 0:00:02
   -------------------- ------------------- 21.5/41.0 MB 10.3 MB/s eta 0:00:02
   --------------------- ------------------ 22.0/41.0 MB 9.6 MB/s eta 0:00:02
   ---------------------- ----------------- 23.1/41.0 MB 9.0 MB/s eta 0:00:02
   ----------------------- ---------------- 24.4/41.0 MB 8.9 MB/s eta 0:00:02
   ------------------------- -------------- 26.2/41.0 MB 8.8 MB/s eta 0:00:02
   --------------------------- ------------ 28.3/41.0 MB 8.8 MB/s eta 0:00:02
   ----------------------------- ---------- 30.4/41.0 MB 8.9 MB/s eta 0:00:02
   ------------------------------- -------- 32.2/41.0 MB 8.9 MB/s eta 0:00:01
   --------------------------------- ------ 34.1/41.0 MB 8.9 MB/s eta 0:00:01
   ----------------------------------- ---- 35.9/41.0 MB 8.8 MB/s eta 0:00:01
   ------------------------------------- -- 38.0/41.0 MB 8.9 MB/s eta 0:00:01
   -------------------------------------- - 39.8/41.0 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  40.9/41.0 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------- 41.0/41.0 MB 8.7 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 threadpoolctl-3.5.0

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [58]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [59]:
scaler = MinMaxScaler()
weather["Temperature_normalized"] = scaler.fit_transform(weather[["Temperature (C)"]])

In [60]:
weather.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary,Temperature_normalized
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.,0.506975
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.,0.505085
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.,0.505445
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.,0.487805
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.,0.495365

In [75]:
pca = PCA(n_components=2)
numeric_cols=weather.select_dtypes(include=['number']).columns
len(numeric_cols)
reduced_weather=pca.fit_transform(weather[(numeric_cols)])
reduced_df=pd.DataFrame(reduced_weather,columns=["PC1","PC2"])
reduced_df

             PC1         PC2
0       7.572204   64.164118
1       7.529264   72.179517
2      11.592634   17.266136
3       7.632113   82.201400
4       8.418255   72.215924
...          ...         ...
96448  21.690263 -155.297113
96449  23.235849 -166.232384
96450  23.064707 -156.242146
96451  24.026120 -166.192174
96452  22.964787 -147.259486

[96453 rows x 2 columns]

In [76]:
average_temp=weather.group_by("Humidity")["Temperature (C)"].mean()
average_temp

AttributeError: 'DataFrame' object has no attribute 'group_by'